name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4 #uses is used to run a specific action. An action is a reusable piece like a function
                                  #actions/checkout is used to checkouts the project source code of Git
        path: ./Pokemon
        
      - uses: actions/setup-node@v4
        with:
          node-version: '20' #setup nodejs to be able to use command in package.json

      - name: Install dependencies
        run: npm install #install dependencies
        working-directory: ./Pokemon

      - name: Check style 
        run: npm run eslint #use command in package.json
        working-directory: ./Pokemon
